from __future__ import annotations

import time
import uuid
from typing import Callable, Iterable, Protocol

from ..models import AgentRow, Question, Status, Task, utcnow


class Board(Protocol):
    def create_task(self, task: Task) -> Task: ...
    def get_task(self, task_id: str, *, page_id: str | None = None,
                 agent: str | None = None) -> Task | None: ...
    def list_tasks(self, *, status: Iterable[Status] | None = None,
                   agent: Iterable[str] | None = None) -> list[Task]: ...
    def update_task(self, task: Task, fields: Iterable[str]) -> Task: ...
    def append_task_report(self, task: Task, heading: str, markdown: str) -> None: ...
    def create_question(self, q: Question) -> Question: ...
    def list_questions(self, *, status: str | None = None) -> list[Question]: ...
    def update_question(self, q: Question, fields: Iterable[str]) -> Question: ...
    def upsert_agent(self, row: AgentRow) -> AgentRow: ...
    def get_agent(self, name: str) -> AgentRow | None: ...
    def list_agents(self) -> list[AgentRow]: ...
    def write_status_page(self, text: str) -> None: ...
    def write_headline(self, text: str, color: str) -> None: ...
    def next_task_id(self) -> str: ...
    def next_question_id(self) -> str: ...


def claim_task(board: Board, task: Task, agent: str, *, sleep: Callable[[float], None] = time.sleep,
               nonce: str | None = None, wait_s: float = 1.5) -> bool:
    """Optimistic claim: write Running + nonce, wait, re-read, confirm the nonce survived."""
    nonce = nonce or uuid.uuid4().hex
    fresh = board.get_task(task.id, page_id=task.page_id or None, agent=agent)
    if fresh is None or fresh.agent != agent or fresh.status not in (Status.READY, Status.CHANGES_REQUESTED):
        return False  # reassigned, cut, or already claimed since we polled
    task.status = Status.RUNNING
    task.claim_nonce = nonce
    task.agent = agent
    task.started = utcnow()
    board.update_task(task, ["status", "claim_nonce", "agent", "started"])
    sleep(wait_s)
    fresh = board.get_task(task.id, page_id=task.page_id or None, agent=agent)
    if fresh is None or fresh.claim_nonce != nonce or fresh.status is not Status.RUNNING:
        return False
    return True
